services:
  devcontainer:
    # Check host system's actual render/video/plugdev group IDs with 'getent group render', 'getent group video', and 'getent group plugdev'
    # Must add these exact IDs in container's group_add section or OpenVINO GPU acceleration will fail
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "256mb"
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      # Use target devcontainer-trt for TensorRT dev
      target: devcontainer
    ## Uncomment this block for nvidia gpu support
    # deploy:
    #       resources:
    #           reservations:
    #               devices:
    #                   - driver: nvidia
    #                     count: 1
    #                     capabilities: [gpu]
    # environment:
    #   YOLO_MODELS: ""
    # devices:
      # - /dev/video0:/dev/video0 # laptop webcam
      # - /dev/bus/usb:/dev/bus/usb # Uncomment for Google Coral USB
      # - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - .:/workspace/frigate:cached
      - ./web/dist:/opt/frigate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug/media:/media/streams:ro
      - ./data/frigate-config:/config
      - ./data/frigate-storage:/media/frigate
     # - /dev/bus/usb:/dev/bus/usb # Uncomment for Google Coral USB
    ports:
      - 5173:5173 # dev frontend
      - "8971:8971"
      - "5001:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
  
  #    - "8555:8555/tcp" # WebRTC over tcp
   #   - "8555:8555/udp" # WebRTC over udp
    #  - "1935:1935" # RTMP feeds
      # - 5321:5321

  mqtt:
    image: eclipse-mosquitto:2.0
    command: mosquitto -c /mosquitto-no-auth.conf # enable no-auth mode
    ports:
      - "1883:1883"

  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./data/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - ./data/home-assistant/run/dbus:/run/dbus:ro
    ports:
      - 1234:8123
networks:
 default:
   driver: bridge